### ISSUE TITLE
a valid BotToken is required

### ISSUE THREAD

**Issue by ethaniel86** [ArnabXD/TGVCBot#191]
I have entered all info in .env but still getting this error prompt 

 tgvcbot@1.1.9 start
 node dist/app.js

[2023-03-28T16:43:55.218] [INFO] - [Running gramJS version 2.15.3]
/root/tgvcbot/node_modules/telegram/client/auth.js:336
        throw new Error("a valid BotToken is required");
              ^

Error: a valid BotToken is required
    at Object.signInBot (/root/tgvcbot/node_modules/telegram/client/auth.js:336:15)
    at TelegramClient.signInBot (/root/tgvcbot/node_modules/telegram/client/TelegramClient.js:233:28)
    at _authFlow (/root/tgvcbot/node_modules/telegram/client/auth.js:360:24)
    at Object.start (/root/tgvcbot/node_modules/telegram/client/auth.js:45:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startUserBot (/root/tgvcbot/dist/userbot.js:21:5)
    at async /root/tgvcbot/dist/app.js:43:5

**Comment by ArnabXD** [comment]
The error here is slightly misleading, by `a valid BotToken` it means a valid session string. This error basically means the `SESSION` you are using is either signed out or wrong or basically not working, try to regenerate session.

**Comment by ethaniel86** [comment]
alright the bot must be logged in to get it work. It is now fixed. Btw can you show some example how to use those commands? 
I tried /youtube <youtube link> it says "xxx Queued at Postion 2 by xxx", how do i play it in group?  Thanks!

**Comment by ArnabXD** [comment]
> alright the bot must be logged in to get it work. It is now fixed. Btw can you show some example how to use those commands? I tried /youtube it says "xxx Queued at Postion 2 by xxx", how do i play it in group? Thanks!

It requires a Bot from botfather and an user account with API_ID, API_HASH & SESSION

You have to start group voice chat on group, add the BOT (from botfather) and USER to that same group and run the commands, incase of joining issues or music not playing, you can run `/stopvc` and run `/yt` or `/jsvn` again.

**Comment by ethaniel86** [comment]
![image](https://user-images.githubusercontent.com/11464581/228543007-0f3bcba9-7f13-407d-abd2-e937bcc69082.png)
Bot replied with this but nothing plays in voice/video chat. Did i miss anything?

**Comment by ArnabXD** [comment]
> ![image](https://user-images.githubusercontent.com/11464581/228543007-0f3bcba9-7f13-407d-abd2-e937bcc69082.png) Bot replied with this but nothing plays in voice/video chat. Did i miss anything?

doesn't look like there is anything wrong from your side, did the user account join voice chat ? (Just in case, you are not using same account to stream and listen right ?)

**Comment by ethaniel86** [comment]
I tested on a new group, i'm the owner. User can hear music when they join the chat but i can't hear anything. hmm...

**Comment by ArnabXD** [comment]
You should use an alternate account to use as the stream account, due to telegram limitations bots from botfather can't stream to voice chat, you need an user account to stream.

**Comment by ArnabXD** [comment]
I am closing this issue, if you still have any issues/doubts you can reopen it
